server:
  port: 5000
spring:
  profiles:
    active: local
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgres://itszlhhc:B0zl8qFyaGh4FIuGBwe0mk8bv-XwASfj@trumpet.db.elephantsql.com/itszlhhc
    username: itszlhhc
    password: B0zl8qFyaGh4FIuGBwe0mk8bv-XwASfj
  cloud:
    function:
      definition:
    stream:
      default-binder: kafka_default
      bindings:
        monitoring-out-0:
          destination: sendtoyou.task-errors
          binder: kafka_default
          useNativeDecoding: true
        newTaskToSchedule-in-0:
          destination: sendtoyou.scheduler-new-task-event
          binder: kafka_default
          useNativeDecoding: true
        newTaskToSchedule-out-0:
          destination: sendtoyou.scheduler-new-task-processed
          binder: kafka_default
          useNativeDecoding: true
        updateJob-in-0:
          destination: sendtoyou.scheduler-new-task-processed
          binder: kafka_default
          useNativeDecoding: true
        updateJob-out-0:
          destination: sendtoyou.scheduler-updateJob
          binder: kafka_default
          useNativeDecoding: true
        duplicateTask-in-0:
          destination: sendtoyou.scheduler-job-triggers
          binder: kafka_default
          useNativeDecoding: true
        duplicateTask-out-0:
          destination: sendtoyou.scheduler-launch-task
          binder: kafka_default
          useNativeDecoding: true
        launcherTasks-in-0:
          destination: sendtoyou.scheduler-launch-task
          binder: kafka_default
          useNativeDecoding: true
        launcherTasks-out-0:
          destination: sendtoyou.scheduler-launchScheduled-task
          binder: kafka_default
          useNativeDecoding: true
        deleteTask-in-0:
          destination: sendtoyou.scheduler-task-to-be-deleted
          binder: kafka_default
          useNativeDecoding: true
        deleteTask-out-0:
          destination: sendtoyou.scheduler-deleted-task
          binder: kafka_default
          useNativeDecoding: true
      binders:
        kafka_default:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    default:
                      consumer:
                        configuration:
                          session.timeout.ms: 60000
                          max.poll.records: 10
                      producer:
                        compressionType: gzip
                        configuration:
                          max.request.size: 322232
                    binder:
                      autoAddPartitions: true
                      autoCreateTopics: true
                      requiredAcks: -1
                      minPartitionCount: 3
                      replicationFactor: 1
                      serdeError: logAndContinue
                      brokers: localhost:9092