server:
  port: 5000
  servlet:
    session:
      timeout: 1800
spring:
  application:
    name: friend-micro-api
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgres://itszlhhc:B0zl8qFyaGh4FIuGBwe0mk8bv-XwASfj@trumpet.db.elephantsql.com/itszlhhc
    username: itszlhhc
    password: B0zl8qFyaGh4FIuGBwe0mk8bv-XwASfj
  cloud:
    function:
      definition:
    stream:
      default-binder: kafka_default
      bindings:
        monitoring-out-0:
          destination: sendtoyou.api-errors
          binder: kafka_default
          useNativeDecoding: true
        packageBinding-out-0:
          destination: sendtoyou.new-package-event
          binder: kafka_default
          useNativeDecoding: true
      binders:
        kafka_default:
          type: kafka
          environment:
            spring:
              profiles:
                active: local