eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      default-zone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
server:
  port: 8761
spring:
  application:
    name: discovery-server