version: '3'

services:
  mariadb:
    container_name: bbdd
    image: mariadb:11.1
    volumes:
      - maria-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
  java:
    container_name: application
    build: .
    depends_on:
      - mariadb
volumes:
  maria-data:
