name: CI Microservices

on:
  pull_request:
    branches:
      - develop  
jobs:
  build-package-api:
    name: Build and Test package API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.6.0

    - name: Set up JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: 17 
        distribution: adopt


    - name: Build with Maven
      run: |
        cd package-micro-api
        mvn clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  build-package:
    name: Build and Test Package Delivery
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.6.0

    - name: Set up JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: 17 
        distribution: adopt


    - name: Build with Maven
      run: |
        cd package-delivery-manager
        mvn clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  build-eligibility:
    name: Build and Test Package Eligibility
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.6.0

    - name: Set up JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: 17 
        distribution: adopt


    - name: Build with Maven
      run: |
        cd package-delivery-manager
        mvn clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn 
